### ISSUE TITLE
ABCurve is not parallel curve

### ISSUE THREAD

**Issue by quentinliao** [farmerbriantee/AgOpenGPS#65]

**Comment by Jmaydavid** [comment]
This would be a really amazing feature... Can't think of much differentiating from the big guys after this...
Maybe as a sub-function within AB curve? So the default AB curve could assume non-circular geometry, which is realistic of most peoples paddocks! But have a button that switches the assumptions of the code to perfect circular geometry so that all AB curves become parallel? Would work perfectly for centre pivots. And use the snap to line to miss the wheel tracks. We would personally pay for someone to code this function...

**Comment by Jmaydavid** [comment]
No idea how complex this would be... but the way JD used to do it in their parallel curves (think they called it pivot pro? A ridiculously expensive add-on) was to set the implement off the wheel track/start of curve (say 100mm) at one end of the pivot track, press point A, then drive round to the other end of the pivot track, set the implement at the exact same distance (100mm), and hit point B. Then I guess with that, computer finds the radii of the arc that intersects both points, and you've got perfect parallel curves?

**Comment by Jmaydavid** [comment]
Well a single AB curve is all that's needed for pivots because the whole paddock works off that same curve/circle. For S curves, probably not. But I mean, the current AB curve works quite well for S-like curves from my testing.

**Comment by quentinliao** [comment]
I tried a lot of ways to achieve parallel curves, but they all failed. Without turning radius control, the vehicle would not be able to drive on the generated curves. But I still haven't found a way to add turning radius control.

**Comment by Jmaydavid** [comment]
Yeah. I've started realising how big this little side venture is... Apparently a Daniel fellow has found/is finding a solution. Would be very interested to see how he does it. 
![photo_2019-08-31_06-42-24](https://user-images.githubusercontent.com/42726782/64143669-73fc4c80-ce54-11e9-90af-f02bc6ca8996.jpg)

**Comment by farmerbriantee** [comment]
Coming to AgOpenGPS shortly!
